import type { Event, FleetAgent, FleetResponse, MemoryItem, Task } from "./types";

const minsAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

// Built per call (not at module load) so timestamps stay fresh on warm
// serverless instances and the demo never contradicts its own status chips.
const buildAgents = (): FleetAgent[] => [
  {
    id: "cowork-cloud-1",
    platform: "cowork-cloud",
    machine: "cloud",
    display_name: "Claude Cowork (cloud)",
    last_seen_at: minsAgo(1),
    derived_status: "active",
    pending_messages: 0,
    unread_replies: 0,
    current_session: {
      id: "sess-cw-001",
      agent_id: "cowork-cloud-1",
      project: "mission-control",
      status: "active",
      summary: "Building the Mission Control dashboard and MCP server",
      started_at: minsAgo(42),
      ended_at: null,
      updated_at: minsAgo(1),
    },
    recent_sessions: [],
  },
  {
    id: "claude-code-macbook-pro",
    platform: "claude-code",
    machine: "macbook-pro-4",
    display_name: "Claude Code (MacBook Pro)",
    last_seen_at: minsAgo(3),
    derived_status: "waiting",
    pending_messages: 1,
    unread_replies: 0,
    current_session: {
      id: "sess-cc-014",
      agent_id: "claude-code-macbook-pro",
      project: "theaie-net",
      status: "waiting",
      summary: "Newsletter page refactor — waiting on permission to push",
      started_at: minsAgo(65),
      ended_at: null,
      updated_at: minsAgo(3),
    },
    recent_sessions: [],
  },
  {
    id: "chatgpt-work-main",
    platform: "chatgpt-work",
    machine: "cloud",
    display_name: "ChatGPT Work",
    last_seen_at: minsAgo(12),
    derived_status: "active",
    pending_messages: 0,
    unread_replies: 0,
    current_session: {
      id: "sess-gpt-007",
      agent_id: "chatgpt-work-main",
      project: "conference-sponsors",
      status: "active",
      summary: "Researching sponsor prospects for All Things AI 2026",
      started_at: minsAgo(30),
      ended_at: null,
      updated_at: minsAgo(12),
    },
    recent_sessions: [],
  },
  {
    id: "hermes-home-server",
    platform: "hermes",
    machine: "home-server",
    display_name: "Hermes",
    last_seen_at: minsAgo(55),
    derived_status: "offline",
    pending_messages: 0,
    unread_replies: 0,
    current_session: null,
    recent_sessions: [
      {
        id: "sess-hm-090",
        agent_id: "hermes-home-server",
        project: "inbox-triage",
        status: "done",
        summary: "Nightly inbox triage and calendar prep",
        started_at: minsAgo(600),
        ended_at: minsAgo(560),
        updated_at: minsAgo(560),
      },
    ],
  },
];

const buildEvents = (): Event[] => [
  { id: 9, agent_id: "cowork-cloud-1", session_id: "sess-cw-001", kind: "milestone", title: "Dashboard UI compiles — starting MCP server endpoint", detail: null, created_at: minsAgo(1) },
  { id: 8, agent_id: "claude-code-macbook-pro", session_id: "sess-cc-014", kind: "notification", title: "Waiting on permission: git push", detail: null, created_at: minsAgo(3) },
  { id: 7, agent_id: "chatgpt-work-main", session_id: "sess-gpt-007", kind: "status", title: "Compiled 22 sponsor prospects, drafting outreach notes", detail: null, created_at: minsAgo(12) },
  { id: 6, agent_id: "cowork-cloud-1", session_id: "sess-cw-001", kind: "turn_start", title: "Build and create in github", detail: null, created_at: minsAgo(20) },
  { id: 5, agent_id: "claude-code-macbook-pro", session_id: "sess-cc-014", kind: "session_start", title: "Session started in ~/code/theaie-net", detail: null, created_at: minsAgo(65) },
  { id: 4, agent_id: "hermes-home-server", session_id: "sess-hm-090", kind: "session_end", title: "Inbox triage complete — 4 items flagged", detail: null, created_at: minsAgo(560) },
];

export const demoMemory = (): MemoryItem[] => [
  {
    id: 3,
    key: "mission-control/decisions",
    content: "Stack: Next.js on Vercel + Neon. Agents push status; nobody polls vendors. MCP server is both telemetry ingest and shared memory.",
    tags: ["mission-control", "architecture"],
    agent_id: "cowork-cloud-1",
    created_at: minsAgo(40),
    updated_at: minsAgo(40),
  },
  {
    id: 2,
    key: null,
    content: "ChatGPT Work is researching sponsors — don't duplicate that work in Cowork. Results land in Notion under Conference/Sponsors.",
    tags: ["all-things-ai", "coordination"],
    agent_id: "chatgpt-work-main",
    created_at: minsAgo(25),
    updated_at: minsAgo(25),
  },
  {
    id: 1,
    key: "newsletter/tangle-monday",
    content: "Monday Tangle draft is staged in Notion awaiting review. Beehiiv send scheduled for 6am ET.",
    tags: ["aie-tangle", "newsletter"],
    agent_id: "hermes-home-server",
    created_at: minsAgo(600),
    updated_at: minsAgo(600),
  },
];

const doneDemoTask = (
  id: number,
  title: string,
  project: string,
  platform: string,
  minutesAgo: number,
  costUsd: number | null,
): Task => ({
  id,
  title,
  description: null,
  project,
  platform,
  machine: null,
  priority: 2,
  status: "done",
  reviewer_platform: id % 2 === 0 ? "codex" : null,
  assigned_agent: `${platform}-macbook-pro`,
  session_id: null,
  result: "Shipped.",
  cost_usd: costUsd,
  created_by: "dashboard",
  created_at: minsAgo(minutesAgo + 90),
  claimed_at: minsAgo(minutesAgo + 60),
  updated_at: minsAgo(minutesAgo),
  completed_at: minsAgo(minutesAgo),
});

export const demoTasks = (): Task[] => [
  // Built history for theaie-net so the demo shows a City of Text monolith.
  doneDemoTask(105, "Ship newsletter signup flow", "theaie-net", "claude-code", 2600, 1.12),
  doneDemoTask(104, "Fix OG images on article pages", "theaie-net", "codex", 2100, 0.38),
  doneDemoTask(103, "Migrate tools directory to CMS", "theaie-net", "claude-code", 1500, 2.4),
  doneDemoTask(102, "Add sponsor placements page", "theaie-net", "grok", 900, 0.55),
  doneDemoTask(101, "SEO pass on landing pages", "theaie-net", "codex", 300, 0.61),
  {
    id: 4,
    title: "Fix broken Beehiiv embed on newsletter page",
    description: "The subscribe embed on /newsletter 404s. Find the current embed id in Beehiiv and update.",
    project: "theaie-net",
    platform: "claude-code",
    machine: null,
    priority: 1,
    status: "queued",
    reviewer_platform: "codex",
    assigned_agent: null,
    session_id: null,
    result: null,
    cost_usd: null,
    created_by: "dashboard",
    created_at: minsAgo(8),
    claimed_at: null,
    updated_at: minsAgo(8),
    completed_at: null,
  },
  {
    id: 3,
    title: "Add speaker headshots to conference page",
    description: null,
    project: "allthingsai-org",
    platform: "codex",
    machine: null,
    priority: 2,
    status: "running",
    reviewer_platform: null,
    assigned_agent: "codex-macbook-pro",
    session_id: null,
    result: null,
    cost_usd: null,
    created_by: "dashboard",
    created_at: minsAgo(35),
    claimed_at: minsAgo(20),
    updated_at: minsAgo(4),
    completed_at: null,
  },
  {
    id: 2,
    title: "Research: agent payments protocols for Deep Dive",
    description: null,
    project: null,
    platform: "grok",
    machine: null,
    priority: 2,
    status: "done",
    reviewer_platform: null,
    assigned_agent: "grok-macbook-pro",
    session_id: null,
    result: "12 sources compiled to memory key deep-dive/agent-payments.",
    cost_usd: 0.42,
    created_by: "cowork-cloud-1",
    created_at: minsAgo(180),
    claimed_at: minsAgo(160),
    updated_at: minsAgo(120),
    completed_at: minsAgo(120),
  },
];

export function demoFleet(): FleetResponse {
  return { demo: true, agents: buildAgents(), events: buildEvents(), generated_at: new Date().toISOString() };
}
